import {getSession,getLocalStorage} from './utils/index'
import {constant} from './constant/index'
let permissionStr = getLocalStorage(constant.PERMISSION)
if(permissionStr){
    permissionStr = JSON.parse(permissionStr)
}
// console.log(permissionStr)

let mock = [
    {
        cUrls: "",
        url: 'index',
        level: 1,
        permissionName: "首页",
        permission: "",
        rank: 1,
        seq: 7,
        type: "1",
        icon: "icon-fengxianjiance",
        id: 7,
        isUse: 1,
        parentId: null,
        child:[
            
        ]
    },
    {
        cUrls: "",
        url: 'riskRecognize',
        level: 1,
        permissionName: "风险识别",
        permission: "",
        rank: 1,
        seq: 7,
        type: "1",
        icon: "icon-fengxianshibie",
        id: 7,
        isUse: 1,
        parentId: null,
        child:[
           {
                cUrls: "roleSet",
                url: 'riskSignalList',
                level: 2,
                permissionName: "风险信号清单",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-fengxianxinhaoqingdan",
                id: 33,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 3,
                type: "1",
            },{
                cUrls: "accountSet",
                url: 'alarmList',
                level: 2,
                permissionName: "预警信号清单",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-yujingxinhaoqingdan",
                id: 23,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 2,
                type: "1",
            }, {
                cUrls: "personalCenter",
                url: 'riskEntList',
                level: 2,
                permissionName: "风险预警清单",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-fengxianqiyeqingdan",
                id: 43,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 4,
                type: "1",
            }, {
                cUrls: "personalCenter",
                url: 'riskReport',
                level: 2,
                permissionName: "风险预警报告",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-fengxianyujingbaogao",
                id: 43,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 4,
                type: "1",
            }
        ]
    },
    {
        cUrls: "",
        url: 'riskResponse',
        level: 1,
        permissionName: "风险响应",
        permission: "",
        rank: 1,
        seq: 7,
        type: "1",
        icon: "icon-fengxianjiance",
        id: 7,
        isUse: 1,
        parentId: null,
        child:[
            
        ]
    },
    {
        cUrls: "",
        url: 'riskMonitor',
        level: 1,
        permissionName: "风险监测",
        permission: "",
        rank: 1,
        seq: 7,
        type: "1",
        icon: "icon-fengxianjiance",
        id: 7,
        isUse: 1,
        parentId: null,
        child:[
            {
                cUrls: "personalCenter",
                url: 'dataset',
                level: 2,
                permissionName: "指标管理",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-zhibiaoguanli",
                id: 43,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 4,
                type: "1",
            }, {
                cUrls: "personalCenter",
                url: 'risksignal',
                level: 2,
                permissionName: "风险信号",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-fengxianxinhao",
                id: 43,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 4,
                type: "1",
            }, {
                cUrls: "roleSet",
                url: 'score',
                level: 2,
                permissionName: "评分卡",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-pingfenka",
                id: 33,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 3,
                type: "1",
            }, {
                cUrls: "personalCenter",
                url: 'alarm',
                level: 2,
                permissionName: "预警信号",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-yujingxinhao",
                id: 43,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 4,
                type: "1",
            }, {
                cUrls: "accountSet",
                url: 'workflow',
                level: 2,
                permissionName: "工作流",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-gongzuoliu",
                id: 23,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 2,
                type: "1",
            }, {
                cUrls: "personalCenter",
                url: 'riskAlert',
                level: 2,
                permissionName: "风险警情表",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-fengxianjingqingbiao",
                id: 43,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 4,
                type: "1",
            }
        ]
    },  {
        cUrls: "",
        url: 'dataCenter',
        level: 1,
        permissionName: "数据中心",
        permission: "",
        rank: 1,
        seq: 7,
        type: "1",
        icon: "icon-shujuzhongxin",
        id: 7,
        isUse: 1,
        parentId: null,
        child:[
            {
                cUrls: "roleSet",
                url: 'statistics',
                level: 2,
                permissionName: "数据统计",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-shujutongji",
                id: 33,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 3,
                type: "1",
            },{
                cUrls: "accountSet",
                url: 'entManage',
                level: 2,
                permissionName: "企业管理",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-qiyeguanli",
                id: 23,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 2,
                type: "1",
            }, {
                cUrls: "personalCenter",
                url: 'entLabel',
                level: 2,
                permissionName: "企业标签管理",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-biaoqianguanli",
                id: 43,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 4,
                type: "1",
            }, {
                cUrls: "personalCenter",
                url: 'dataImport',
                level: 2,
                permissionName: "数据导入列表",
                description: '这个业务的简单解释这个业务的简单解释这个业务的简单解释这个业务的简单解释',
                icon: "icon-shujudaoru",
                id: 43,
                isUse: 1,
                parentId: 1,
                permission: "",
                rank: 1,
                seq: 4,
                type: "1",
            }
        ]
    },  {
        cUrls: "",
        url: 'entPortrait',
        level: 1,
        permissionName: "企业画像",
        permission: "",
        rank: 1,
        seq: 7,
        type: "1",
        icon: "icon-qiyehuaxiang",
        id: 7,
        isUse: 1,
        parentId: null,
        child:[
        ]
    }
    
    

]
export const permission = permissionStr ? mock : mock;